<a href="https://colab.research.google.com/github/chenniuzidadan/chenniuzidadan/blob/main/pytorch_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)i

2.5.1+cu121


In [8]:
## saclar
scalar=torch.tensor(7)
scalar

tensor(7)

In [9]:
## x is vector
x=torch.tensor([1,2,3,4,5])
print(x)

tensor([1, 2, 3, 4, 5])


In [11]:
y=torch.rand(2,3)
print(y)


tensor([[0.4696, 0.0852, 0.2312],
        [0.9375, 0.2792, 0.3916]])


In [12]:
scalar.ndim


0

In [14]:
scalar.item()


7

In [17]:
## vector
x.ndim


1

In [18]:
x.shape


torch.Size([5])

In [21]:
## Matrix
Matrix=torch.tensor([[1,2],[3,4]])
print(Matrix)

tensor([[1, 2],
        [3, 4]])


In [22]:
Matrix.ndim


2

In [23]:
Matrix.shape

torch.Size([2, 2])

In [24]:
Matrix[1]

tensor([3, 4])

In [26]:
TENSOR=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
TENSOR


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])